# dein_lazy.toml

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>'
on_path = '.*'

[[plugins]]
repo = 'lambdalisue/vim-gita'
on_cmd = 'Gita'

[[plugins]]
repo = 'cohama/agit.vim'
on_map = ['[git]']

[[plugins]]
repo = 'gregsexton/gitv'
on_map = ['[git]']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'rhysd/try-colorscheme.vim'
on_cmd = 'TryColorscheme'

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['unite', 'quickfix']

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_map = '<Plug>'
on_path = '.*'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>'
on_path = '.*'


#-------------------------------------------------------------------------------
# File type
#
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = ['jade']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'ctp', 'php']

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php', 'jade', 'ctp']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['styl', 'stylus']

[[plugins]]
repo = 'vim-scripts/css_color.vim'
on_ft = ['css']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

