#
# dein_lazy_plugins.toml
#

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_add = 'nnoremap <silent>   [Space]v   :<C-u>VimFiler -invisible<CR>'
hook_source = '''
call vimfiler#custom#profile('default', 'context', {
      \ 'safe' : 0,
      \ 'auto_expand' : 1,
      \ 'parent' : 0,
      \ })
let g:vimfiler_as_default_explorer = 1

let g:vimfiler_tree_leaf_icon = ' '
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
let g:vimfiler_file_icon = ' '
let g:vimfiler_readonly_file_icon = '✗'
let g:vimfiler_marked_file_icon = '✓'
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_source = 'denite.nvim'
#hook_source = 'source ~/.vim/rc/plugins/unite.rc.vim'
hook_add = '''
  nnoremap <silent> <C-k>
        \ :<C-u>Unite change jump<CR>
  nnoremap <silent> <C-t>
        \ :<C-u>Unite -auto-resize -select=`tabpagenr()-1` tab<CR>
  " Tag jump.
  nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
        \ ":\<C-u>UniteWithCursorWord -buffer-name=tag -immediately
        \  tag tag/include\<CR>"
  nnoremap <silent><expr> tp  &filetype == 'help' ?
        \ ":\<C-u>pop\<CR>" : ":\<C-u>Unite jump\<CR>"
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
  nnoremap <silent> ;r
        \ :<C-u>Denite -buffer-name=register unite:register neoyank<CR>
  nnoremap <silent> [Space]q
        \ :<C-u>Denite file_rec:~/.vim/rc<CR>
  nnoremap <silent> / :<C-u>Denite -buffer-name=search line<CR>
  nnoremap <silent> * :<C-u>DeniteCursorWord -buffer-name=search line<CR>
  nnoremap <silent> ;g :<C-u>Denite -buffer-name=search -no-empty grep<CR>
  nnoremap <silent> n :<C-u>Denite -buffer-name=search -resume -mode=normal<CR>
  nnoremap <silent> ft :<C-u>Denite filetype<CR>
  nnoremap <silent> <C-t> :<C-u>Denite unite:tab -select=`tabpagenr()-1` -mode=normal<CR>
  nnoremap <silent> gr :<C-u>Denite file_rec<CR>

  nnoremap [Denite] <Nop>
  nmap     [Space]d [Denite]
  nnoremap <silent> [Denite]s :<C-u>Denite file_point file_mru
        \ `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'`<CR>
  nnoremap <silent> [Denite]n :<C-u>Denite dein<CR>
  nnoremap <silent> [Denite]g :<C-u>Denite ghq<CR>
  nnoremap <silent> [Denite]m :<C-u>Denite menu<CR>
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['php', 'html', 'css', 'pug']

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'nixprime/cpsm'
on_source = 'denite.nvim'
build = 'env PY3=ON ./install.sh'

[[plugins]]
repo = 'h1mesuke/vim-alignta'
hook_source = 'source ~/.vim/rc/plugins/alignta.rc.vim'
on_i = 1
