# EDITOR
export GIT_EDITOR=vim

# vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox

# sbin
export PATH=$PATH:/sbin:/usr/sbin

# Homebrew
export PATH=/usr/local/bin:$PATH
# Homebrew cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Tools
export PATH=$PATH:~/tools/bin

# NeoVim
export XDG_CONFIG_HOME=~/.config


# GO
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/code/golang
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin


# rbenv
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"


# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=$HOME/tools/cocos2d-x-3.11/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_X_ROOT for cocos2d-x
export COCOS_X_ROOT=$HOME/tools
export PATH=$COCOS_X_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=$HOME/tools/cocos2d-x-3.11/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH


# EMSDK Portable
export EM_CONFIG=$HOME/.emscripten
export EMSCRIPTEN=$HOME/tools/emsdk_portable/emscripten/1.35.0
export PATH=$HOME/tools/emsdk_portable/clang/e1.35.0_64bit:$PATH
export PATH=$HOME/tools/emsdk_portable/node/4.1.1_64bit/bin:$PATH
export PATH=$HOME/tools/emsdk_portable/emscripten/1.35.0:$PATH
