# EDITOR
export GIT_EDITOR=vim

# vagrant
export VAGRANT_DEFAULT_PROVIDER=virtualbox

# sbin
export PATH=$PATH:/sbin:/usr/sbin

# Homebrew
export PATH=/usr/local/bin:$PATH
# Homebrew cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Tools
export PATH=$PATH:~/tools/bin

# NeoVim
export XDG_CONFIG_HOME=~/config

